name: CI

on:
  push:
    branches:
      - develop

# -------------------------------
#  Optionally run on other events
# -------------------------------
#  schedule:
#     - cron: '0 0 * * *'
#
#  release:
#    types: [...]
#
#  workflow_dispatch:
#
#  push:
#    tags:
#      - '**'
#
#  merge_group:
#
# ...and many more
env:
  AWS_REGION: ap-northeast-1                   # set this to your preferred AWS region, e.g. us-west-1


permissions:
  id-token: write
  contents: read


jobs:
  # -------------------------------------------------------------
  # Using GitHub's API is not supported for push events
  # -------------------------------------------------------------
  #
  # ----------------------------------------------------------------------------------------------
  # Using local .git history
  # ----------------------------------------------------------------------------------------------
  # Event `push`: Compare the preceding remote commit -> to the current commit of the main branch
  # ----------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest  # windows-latest || macos-latest
    name: Test changed-files
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::329872142039:role/github-action-role
          role-session-name: testRoleSession

      - name: get build time
        id: build-time
        run: echo "buildtime=$(date +%Y%m%d%H%M%S)" >> $GITHUB_OUTPUT

      - name: S3 upload
        run: |
          aws s3 cp ./src/main/resources/static/ s3://kiss-yerim-test/static/ --recursive --exclude "*" --include "*.js" --include "*.css"
          
          
